matrix:
  include:
    - language: go
      go:
        - 1.12
      cache:
        directories:
          - $GOPATH/pkg/mod
      install:
        - cd api && make install
      script:
        - cd api && make lint
        - cd api && make test
    - language: node_js
      node_js:
        - '10'
      cache:
        directories:
          - web/node_modules
      before_install:
        - cd web && npm install -g npm@latest
      script:
        - npm test
