matrix:
  include:
    - language: go
      go:
        - 1.12
      cache:
        directories:
          - $GOPATH/pkg/mod
      before_install:
        - cd api
      install:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
        - make install
      script:
        - make lint
        - make test
    - language: node_js
      node_js:
        - '10'
      cache:
        directories:
          - web/node_modules
      before_install:
        - cd web
        - npm install -g npm@latest
      script:
        - npm test
