matrix:
  include:
    - language: go
      go:
        - 1.12
      cache:
        directories:
          - $GOPATH/pkg/mod
      install:
        - cd api && make install
      script:
        - cd api && make lint
        - cd api && make test
