matrix:
  include:
    - language: go
      go:
        - 1.12
      cache:
        directories:
          - $GOPATH/pkg/mod
      before_install:
        - cd api
      install:
        - make install
      script:
        - make lint
        - make test
    - language: node_js
      node_js:
        - '10'
      cache:
        directories:
          - web/node_modules
      before_install:
        - cd web
        - npm install -g npm@latest
      script:
        - npm test
